
name: Build-Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Checkout Target
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout Dependencies (BeamGameCode)
      uses: actions/checkout@v2
      with:
        repository: Apian-Framework/BeamGameCode
        path: BeamGameCode

    - name: Checkout Apian dependencies (Apian)
      uses: actions/checkout@v2
      with:
        repository: Apian-Framework/Apian.Net
        path: Apian.Net

    - name: Checkout Apian dependencies (NotUnityEngine)
      uses: actions/checkout@v2
      with:
        repository: Apian-Framework/NotUnityEngine
        path: NotUnityEngine

    - name: Install dependencies
      run: dotnet restore
      working-directory: main

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: main

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: main